Network:
  epochs: 300 # 300
  batch_size: 128 # 256
  sample_batch_size: 64 # 128
  n_steps: 8 # timestep   16
  dataset: "CIFAR10"
  in_channels: 3
  data_path: "/data/zhan/CV_data/cifar10"
  lr: 0.0001 # 0.0006
  sample_layer_lr_times: 10
  n_class: 10
  latent_dim: 128
  input_size: 32
  model: "SAE" # "ESVAE" # ESVAE or ESVAE_large
  k: 20 # multiplier of channel
  scheduled: true # whether to apply scheduled sampling
  loss_func: 'mmd' # mmd or kld
  mmd_type: 'rbf'
  mu: 0.0  # the mu of the normal distribution of the sampled latent vector in generating stage
  var: 1.0  # the mu of the normal distribution of the sampled latent vector in generating stage
  distance_lambda: 0.001
  boundary_weight: 0.005  # 新增

  