Network:
  epochs: 200
  batch_size: 256 # 256
  sample_batch_size: 256
  n_steps: 16 # timestep
  dataset: "FashionMNIST"
  in_channels: 1
  data_path: "/home/user/kpm/data/fashion-mnist-master/data/fashion" # "/data/zhan/CV_data/FashionMNIST"
  lr: 0.0001 # 0.00005
  sample_layer_lr_times: 10
  n_class: 10
#  latent_dim: 32 # 128
  latent_dim_recon: 32  # 重构任务的潜在维度
  latent_dim_class: 512    # 分类任务的潜在维度
  input_size: 32
  model: "SAE" # "ESVAE" # ESVAE or ESVAE_large
  k: 20 # multiplier of channel
  scheduled: true # whether to apply scheduled sampling
  loss_func: 'mmd' # mmd or kld
  mmd_type: 'rbf'
  mu: 0.0  # the mu of the normal distribution of the sampled latent vector in generating stage
  var: 1.0  # the mu of the normal distribution of the sampled latent vector in generating stage
  distance_lambda: 0.001
  boundary_weight: 0.001  # 新增
  